
export const COLORS = {
  PRIMARY_GOLD: '#D4AF37',
  SILVER: '#E5E7EB',
  DARK_BURGUNDY: '#4A0404',
  DEEP_MAROON: '#2D0202',
  TEXT_LIGHT: '#F5F5F5',
  TEXT_DARK: '#333333',
  TEXT_GRAY: '#777777',
  SUCCESS_GREEN: '#2E7D32',
  ERROR_RED: '#C62828',
  WHITE: '#FFFFFF',
  OFF_WHITE: '#F9F9F9'
};

export const STRINGS = {
  APP_NAME: 'SU Salon',
  LOGIN: 'تسجيل دخول',
  SIGNUP: 'إنشاء حساب',
  LOGOUT: 'تسجيل خروج',
  USER_TYPE_CLIENT: 'عميل',
  USER_TYPE_EXPERT: 'خبير',
  GENDER_MALE: 'ذكر',
  GENDER_FEMALE: 'أنثى',
  NAME_LABEL: 'الاسم الكامل',
  EMAIL_LABEL: 'البريد الإلكتروني',
  PHONE_LABEL: 'رقم الهاتف',
  AGE_LABEL: 'العمر',
  GENDER_LABEL: 'الجنس',
  TYPE_LABEL: 'نوع الحساب',
  ID_UPLOAD_LABEL: 'رفع صورة الهوية',
  NEXT: 'التالي',
  BACK: 'رجوع',
  FINISH: 'إتمام التسجيل',
  MAP_VIEW: 'الخريطة',
  LIST_VIEW: 'القائمة',
  DASHBOARD: 'لوحة التحكم',
  WALLETS: 'المحفظة',
  POINTS: 'النقاط',
  SETTINGS: 'الإعدادات',
  ORDERS: 'الطلبات',
  BOOK_NOW: 'احجز الآن',
  TOTAL_PRICE: 'السعر الإجمالي',
  BIO: 'النبذة التعريفية',
  PORTFOLIO: 'معرض الأعمال',
  ADD_PHOTO: 'إضافة صورة',
  SERVICES: 'الخدمات والأسعار',
  ADD_SERVICE: 'إضافة خدمة',
  SERVICE_NAME: 'اسم الخدمة',
  SERVICE_PRICE: 'السعر (ر.س)',
  SERVICE_DURATION: 'المدة (دقيقة)',
  CLIENT_LOCATION: 'موقع العميل',
  ACCEPT_REQUEST: 'قبول الطلب',
  REJECT_REQUEST: 'رفض الطلب',
  EXPERT_PROFILE: 'ملف الخبير',
  REQUEST_SENT: 'تم إرسال طلبك بنجاح'
};
